---
title: "PIGEON3.0"
output: pdf_document
date: "2025-11-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(metagear)
library(readxl)
##reference set cleaning -- from a Web of Science search export as tab delimited and then delete everything except TITLE, AUTHORS, ABSTRACT (pages and journal if you want, metagear needs the 1st three). Rename TITLE, AUTHORS, ABSTRACT as capitalized here


##read in the cleaned list of studies, lives in PIGEON3.0 Team Stage01-DatasetCuration/Screening
refs<-read.csv("../WoS_search_120125/combined_cleaned_refs_120125.csv",header = TRUE,stringsAsFactors = FALSE)

```

```{r}
setwd("../PIGEON")

#Effort distribution, do not rerun this if your effort files have already been created
effort_distribute(refs, #list of cleaned references to screen
              reviewers=c("rev1","rev2","rev3","rev4"), #reviewers you want to split the effort amongst
              initialize=TRUE,
                  save_split = TRUE, #save the split effort files into your working directory
                  directory="../PIGEON") #define the directory 
#Can add dual=TRUE to double up on screening if you want, need an even # of reviewers

```

```{r}
initial_screeningresults<-read_xlsx(="../combined_cleaned_refs_120125.xlsx",sheet=2)

fullscreening_fullrefs<-read_xlsx("../fullrefs_cleaned.xlsx",sheet=1)


screen2list<-left_join(initial_screeningresults, fullscreening_fullrefs, by=c("AUTHORS","TITLE","ABSTRACT"))


effort_distribute(screen2list, #list of cleaned references to screen
              reviewers=c("rev1","rev2","rev3","rev4"), #reviewers you want to split the effort amongst
              initialize=TRUE,
                  save_split = TRUE, #save the split effort files into your working directory
                  directory="../PIGEON3.0 - screening/screen2")

```

##PIGEON3 MAP
```{r}
## Panel B
# Load coordinates data for PIGEON mapping
suppressMessages(library(readxl))
suppressMessages(library(ggplot2))
suppressMessages(library(rnaturalearth))
suppressMessages(library(rnaturalearthdata))
suppressMessages(library(sf))
suppressMessages(library(ggrepel))
suppressMessages(library(tidyverse))
suppressMessages(library(dplyr))

pigeon3 <- read_xlsx("../PIGEON/PEONY_PIGEON3_metadata_Sep2026.xlsx",sheet=1)
 
# Filter out all no coordinates reads.
  
world <- ne_countries(scale = "medium", returnclass = "sf")

pigeon3_map_clean <- pigeon3 %>%
  # convert lat/lon to numeric (non-convertible -> NA)
  dplyr::mutate(
    lat = as.numeric(latitude),
    lon = as.numeric(longitude)
  ) %>%
  # filter out bad rows
  filter(
    !is.na(lat),
    !is.na(lon))

pigeon3_map <- pigeon3_map_clean %>%
  dplyr::group_by(habitat,habitat_sub1, lat, lon, country) %>%
  dplyr::summarise(
    n_vOTUs = sum(num_vOTUsPIGEON3, na.rm = TRUE),
    .groups = "drop"
  )
 
# make sure df_map is numeric and habitat_type is factor
pigeon3_map <- pigeon3_map %>%
  mutate(
    lat = as.numeric(lat),
    lon = as.numeric(lon),
    habitat = factor(habitat), 
    habitat1= factor(habitat_sub1),
    country=factor(country)
  )

  
habitat_cols<-c("Aquatic"="dodgerblue4",  "Digestive"="hotpink", "Other"="gray", "Peat"="orange", "Soil"="tan4")

habitat_sub1_col<-c("Peat"="darkorange2",  "Rhizosphere"="darkolivegreen1",  "Agricultural"="tan4", "Wetland" = "darkolivegreen4", "Forest"="forestgreen" ,  "Marine"="turquoise" ,    "Other"="grey","Grassland"="gold",    "Freshwater" ="dodgerblue" , "Chaparral"="firebrick", "Digestive"="hotpink" )

pigeon3_map$habitat1<-factor(pigeon3_map$habitat1, levels=c("Agricultural", "Forest","Grassland","Wetland","Rhizosphere","Chaparral","Peat","Marine","Freshwater", "Digestive","Other"))


pigeon3_map$habitat<-factor(pigeon3_map$habitat, levels=c("Aquatic","Soil","Peat","Digestive","Other"))

# World map
worldpigeon3 <- ggplot() +
  geom_sf(data = world, fill = "grey95", color = "grey70", linewidth = 0.2) +
  geom_point(
    data = pigeon3_map,
    aes(x = lon, y = lat, size = n_vOTUs/1000, fill = habitat1),
    shape = 21,
    color = "black",
    alpha = 0.75
  ) +
  # size scaling: sqrt transform so small counts are bigger visually
  scale_size_area(
    max_size = 8,
    name = "Number of vOTUs (x1000)",
    breaks = c(1,10,50, 100, 300),  # optional nice legend
    trans = "sqrt"
  ) +
  scale_fill_manual(values = habitat_sub1_col) +
  coord_sf(expand = FALSE) +
  theme_minimal() +
  guides(
    # Override key/marker size specifically for the color legend
    fill = guide_legend(override.aes = list(size = 6)) 
  )+
   theme(
    panel.grid = element_blank(),
    legend.position = "right",legend.direction = "vertical",
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 11)
      ) +
   labs(
    x = NULL,
    y = NULL,
    fill = "Sample type"
  )
worldpigeon3

ggsave("worldmap_pigeon3.svg",width=12,height=6,dpi=300,path="../PIGEON")
 
```
 ##PIGEON PIECHART
```{r}

habitat_summ<-pigeon3 %>%
  dplyr::group_by(habitat_sub1) %>%
  dplyr::summarise(totalvotus=sum(num_vOTUsPIGEON3))

soil<-pigeon3[which(pigeon3$habitat=="Soil"),]

# 1. Set factor levels explicitly
habitat_summ_labeled <- habitat_summ %>%
  dplyr::mutate(habitat = factor(habitat_sub1, levels = c("Agricultural", "Forest","Grassland","Wetland","Rhizosphere","Chaparral","Peat","Marine","Freshwater", "Digestive","Other"))) %>%
  # 2. Arrange by factor levels in REVERSE order to match ggplot's stacking behavior
 # dplyr::arrange(desc(habitat_sub1)) %>%
  # 3. Calculate the correct midpoints
  dplyr::mutate(
    pos = cumsum(totalvotus) - (totalvotus / 2),
    label_text2 = paste0(round(totalvotus / sum(totalvotus) * 100, 1), "%")
  )


pigeon3.0_habitat_L1<-ggplot(habitat_summ_labeled, aes(x = "", y = totalvotus, fill = habitat)) +
  geom_bar(stat = "identity", width = 1, position = position_stack(reverse=TRUE)) +
  coord_polar("y", start = 0) +
  theme_void()+
  scale_fill_manual(values=habitat_sub1_col)+
  geom_text_repel(data=habitat_summ_labeled, aes(label = label_text2),position=position_stack(vjust=0.5, reverse=TRUE), color = "black", size = 4) +
  labs(fill="Habitat")+
  ggtitle("PIGEON3.0 1,351,223 vOTUs")+
  theme(title = element_text(size=20,color="black"), legend.text = element_text(size=18,color="black"), axis.text.y = element_text(size=18,color="white"))
  # Removes background grid and axes

pigeon3.0_habitat_L1

ggsave("pigeon3.0_habitat_L1.svg",width=5,height=4,dpi=300,path="../PIGEON")

```

PEONY1.0 PIECHART
```{r}
peony<-pigeon3_map_clean[which(pigeon3_map_clean$includedinPEONY=="yes"),]

peony$habitat<-factor(peony$habitat)
peony$habitat_sub1<-factor(peony$habitat_sub1)
peony$num_vOTUs_PEONY1<-as.numeric(peony$num_vOTUs_PEONY1)

habitat_summ_peony<-peony %>%
  dplyr::group_by(habitat_sub1) %>%
  dplyr::summarise(totalvotus=sum(num_vOTUs_PEONY1))

habitat_summ_labeled_peony <- habitat_summ_peony %>%
  dplyr::mutate(habitat = factor(habitat_sub1, levels = c("Agricultural", "Forest","Grassland","Wetland","Rhizosphere","Chaparral","Peat","Marine","Freshwater", "Digestive","Other"))) %>%
  # 2. Arrange by factor levels in REVERSE order to match ggplot's stacking behavior
 # dplyr::arrange(desc(habitat_sub1)) %>%
  # 3. Calculate the correct midpoints
  dplyr::mutate(
    pos = cumsum(totalvotus) - (totalvotus / 5),
    label_text2 = paste0(round(totalvotus / sum(totalvotus) * 100, 1), "%")
  )

peony_habitat_L1<-ggplot(habitat_summ_labeled_peony, aes(x = "", y = totalvotus, fill = habitat)) +
  geom_bar(stat = "identity", width = 1, position = position_stack(reverse=TRUE)) +
  coord_polar("y", start = 0) +
  theme_void()+
  scale_fill_manual(values=habitat_sub1_col)+
  geom_text_repel(data=habitat_summ_labeled_peony, aes(label = label_text2),position=position_stack(vjust=0.5, reverse=TRUE), color = "black", size = 4) +
  labs(fill="Habitat")+
  ggtitle("PEONY1.0 1,072,861 vOTUs")+
  theme(title = element_text(size=20,color="black"), legend.text = element_text(size=18,color="black"), axis.text.y = element_text(size=18,color="white"))
  # Removes background grid and axes


  # Removes background grid and axes

peony_habitat_L1

ggsave("peony_pie_91026.svg",width=5,height=4,dpi=300,path="../PIGEON/figs")

##habitat2

```

##PEONY MAP
```{r}
peony<-pigeon3_map_clean[which(pigeon3_map_clean$includedinPEONY=="yes"),]

peony$num_vOTUs_PEONY1<-as.numeric(peony$num_vOTUs_PEONY1)

peony_map <- peony %>%
  dplyr::group_by(habitat,habitat_sub1, latitude, longitude, country) %>%
  dplyr::summarise(
    n_vOTUs = sum(num_vOTUs_PEONY1, na.rm = TRUE),
    .groups = "drop"
  )
 
# make sure df_map is numeric and habitat_type is factor
peony_map <- peony_map %>%
  dplyr::mutate(
    lat = as.numeric(latitude),
    lon = as.numeric(longitude),
    habitat = factor(habitat), 
    habitat_sub1= factor(habitat_sub1),
    country=factor(country)
  )

# World map
worldpeony <- ggplot() +
  geom_sf(data = world, fill = "grey95", color = "grey70", linewidth = 0.2) +
  geom_point(
    data = peony_map,
    aes(x = lon, y = lat, size = n_vOTUs/1000, fill = habitat_sub1),
    shape = 21,
    color = "black",
    alpha = 0.75
  ) +
  # size scaling: sqrt transform so small counts are bigger visually
  scale_size_area(
    max_size = 8,
    name = "Number of vOTUs (x1000)",
    breaks = c(1, 10, 50, 100, 300),  # optional nice legend
    trans = "sqrt"
  ) +
  scale_fill_manual(values = habitat_sub1_col) +
  coord_sf(expand = FALSE) +
  theme_minimal() +
  guides(
    # Override key/marker size specifically for the color legend
    fill = guide_legend(override.aes = list(size = 8)) 
  )+
   theme(
    panel.grid = element_blank(),
    legend.position = "bottom",legend.direction = "horizontal",
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 11)
      ) +
   labs(
    x = NULL,
    y = NULL,
    fill = "Sample type"
  )
worldpeony

ggsave("world_peony_91026.svg",width=12,height=6,dpi=300,path="../PIGEON/figs")
```
##California only
 
```{r}
########## California only
# Filter to California only
 
peony_CA <- peony_map %>%
  filter((lat >= 32 & lat <= 42 & lon >= -125 & lon <= -114))
 
#########

# Load US states
us_states <- ne_states(country = "United States of America",
                       returnclass = "sf")
 
# Extract California
california <- us_states %>%
  filter(name == "California")
 
peony_CA_map <- peony_CA %>%
  filter(country == "USA",
         lat > 32, lat < 42,
         lon > -125, lon < -114)
 
peony1_CA <- ggplot() +
  geom_sf(
    data = california,
    fill = "grey95",
    color = "black",
    linewidth = 0.4
  ) +
  geom_point(
    data = peony_CA_map,
    aes(x = lon, y = lat, size = n_vOTUs/1000, fill = habitat_sub1),
    shape = 21,
    color = "black",
    alpha = 0.6,
    position = position_jitter(width = 0.08, height = 0.08)
  ) +
  scale_size_area(
    max_size = 20,
    name = "Number of vOTUs x1000",
    trans = "sqrt",
    breaks = c(1, 10, 100, 1000)
  ) +
  scale_fill_manual(values = habitat_sub1_col) +
  coord_sf(
    xlim = st_bbox(california)[c("xmin", "xmax")],
    ylim = st_bbox(california)[c("ymin", "ymax")],
    expand = FALSE
  ) +
  guides(
    # Override key/marker size specifically for the color legend
    fill = guide_legend(override.aes = list(size = 8)) 
  )+
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "right", legend.direction = "horizontal",
    title = element_text(size=14, color="black"))+
  labs(
    x = NULL,
    y = NULL,
    fill = "Sample type",
    title = "California vOTU\nSampling Sites"
  )
peony1_CA
 
ggsave("peony1_CA_91026.svg",width=12,height=6,dpi=300,path="../PIGEON/figs")
 
```